### ISSUE TITLE
star一下，等一波用户系统

### ISSUE THREAD

**Issue by Yimien** [Y80/bmm#24]
不太喜欢依靠外部授权登录的方式，最重要的是，我想在内网使用。大佬有没有考虑出方便部署的docker镜像，将需要手动修改的数据开放成环境变量应该会更容易部署。

**Comment by xubillde** [comment]
+1

**Comment by Y80** [comment]
「需要手动修改的数据」具体是指哪些？

**Comment by xubillde** [comment]
需要手动修改的数据，这个我估计就是docker的几个环境变量，现在就有支持，后续内网使用的话，应该不要github相关的变量了，可能变更成数据库之类的。具体等 @Yimien回复。

**Comment by Yimien** [comment]
如果是做成镜像的话，那些需要手动修改的.env里的变量就可以做成环境变量开放出来，包括数据库的切换和账号密码配置之类的

**Comment by Y80** [comment]
当前支持使用 docker compose 部署应用，相比 docker 镜像有什么缺点吗？我对 docker 不太熟 ：）

**Comment by Yimien** [comment]
目前的确是支持 docker compose，只不过需要在部署前需要进行一次编译生成镜像，目前主要还是部署相对来说比较麻烦，理想情况下的部署不需要去修改仓库文件的，而且目前一但你更新代码，当我们想要更新的话，需要通过git重新拉取，合并代码，然后再进行部署。但如果你出了镜像，我只需要删掉原来部署的，然后用原来的docker compose部署文件就可以直接部署成功。

优点在于：
第一，更新维护更简单；
第二，减少部署时间，因为不需要部署前再编译生成镜像；
第三，减少一些本不需要发生的错误，比如```docker compose up -d```这个命令我在部署时就无效，需要改成```docker-compose up -d```，又或者在编译时需要下载镜像，但是提示下载失败，我需要查看Dockerfile，然后去手动拉取一次镜像才能编译成功，等部署完又要清理掉这些因为编译才下载的镜像。

总结起来就是，可以降低部署难度，减少部署时间，以及避免空间浪费，有利于更新维护。

**Comment by Yimien** [comment]
而且当部署使用的数据库可以通过开放环境变量来控制，不需要让用户再去修改代码。

至于切换的方法，你也只需要标注一下开放出来的环境变量是做什么的，该写什么，这样就行了，比让用户修改代码要简单多了。

**Comment by Yimien** [comment]
账户密码就足够了，如果有需要的话也可以加上邮箱验证后可通过邮箱登录，这其实都可以，主要是用github授权登录这个操作确实少见，当然，现在用github授权内网也是可以登录的。

**Comment by Y80** [comment]
> 目前的确是支持 docker compose，只不过需要在部署前需要进行一次编译生成镜像，目前主要还是部署相对来说比较麻烦，理想情况下的部署不需要去修改仓库文件的，而且目前一但你更新代码，当我们想要更新的话，需要通过git重新拉取，合并代码，然后再进行部署。但如果你出了镜像，我只需要删掉原来部署的，然后用原来的docker compose部署文件就可以直接部署成功。
> 
> 优点在于： 第一，更新维护更简单； 第二，减少部署时间，因为不需要部署前再编译生成镜像； 第三，减少一些本不需要发生的错误，比如`docker compose up -d`这个命令我在部署时就无效，需要改成`docker-compose up -d`，又或者在编译时需要下载镜像，但是提示下载失败，我需要查看Dockerfile，然后去手动拉取一次镜像才能编译成功，等部署完又要清理掉这些因为编译才下载的镜像。
> 
> 总结起来就是，可以降低部署难度，减少部署时间，以及避免空间浪费，有利于更新维护。

@Yimien 你的意思是根据目前项目中已有的 `Dockerfile` 构建镜像吗？启动服务还是靠 docker-compose ？我之前理解的是把 Next.js 和 PostgreSQL 打包进一个镜像，然后通过 `docker run` 启动整个应用。但是我了解到：单容器多进程模式不符合生产环境最佳实践」。

**Comment by Yimien** [comment]
没有必要把 Next.js 和 PostgreSQL 一起打包成一个镜像，因为你的项目基本上是可以支持多种数据库部署的，你可以只打包 Next.js 的镜像，然后通过环境变量来配置数据库的信息，因为可能存在这么一种情况：用户已经部署了 PostgreSQL 或者 mysql 之类的数据库，他们不想过多浪费资源。

比如 Gitea 的部署就支持很多种数据库：
```
version: "3"
services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=192.168.31.109:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=iqV1Ci$^w42xsA!e
    restart: unless-stopped
    network_mode: "bridge"
    volumes:
      - ./data:/data
      - /volume1/git:/data/git/repositories
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "22:22"
```
它通过 `GITEA__database__DB_TYPE` 来指定数据库类型，其它的环境变量如 `GITEA__database__HOST` 来指定数据库地址等等，这是一种情况。

还有一种情况就是用户没有部署过数据库，这时候你源码里的 docker compose 文件修改一下就可以用了，至于修改的部分就是把`image` 都改成 `gitea/gitea:latest` 这样的云端拉取而不是本地编译
