### ISSUE TITLE
怎么不使用GitHub授权登录，直接docker compose配置账号密码登录

### ISSUE THREAD

**Issue by qiyue-sanye** [Y80/bmm#47]
用飞牛os的docker搭建，3000端口已经占用了，修改完发现GitHub的授权还是3000端口，所以修改配置内部端口无效

用deepseek摸出来用docker compose构建项目，但是用GitHub登录授权时页面提示

What‽
Your browser did something unexpected. Please try again. If the error continues, try disabling all browser extensions.

Please contact us if the problem persists.

或者返回禁止

所以能不能不用GitHub

如果需要使用docker compose搭建的可以看一下，参考，

**端口已改回3000**

```
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgresql
    environment:
      POSTGRES_DB: bmm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 523f2vmYf4HIwR #可以改需要和下面的DB_CONNECTION_URL一样
    volumes:
      - 想存放的位置地址:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bmm"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  bmm:
    image: lcclcc/bmm
    container_name: bmm
    restart: unless-stopped
    environment:
      - DB_DRIVER=postgresql
      - DB_CONNECTION_URL=postgresql://postgres:523f2vmYf4HIwR@postgres:5432/bmm
      - HOST=0.0.0.0
      - PORT=3000 #内部端口
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
      echo '等待数据库准备就绪...';
      while ! nc -z postgres 5432; do
        echo '数据库端口尚未开放，等待...';
        sleep 2;
      done;
      echo '数据库端口已开放，启动应用...';
      pnpm start --port 3000
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s

```

**Comment by Y80** [comment]
bmm 并不支持账号密码的登录方式，短期内也不考虑支持。

如果需要实现 Github 授权回调地址的端口和你配置的项目端口一致，你需要补充下配置：

```yml
  bmm:
    image: lcclcc/bmm
    # ...
    environment:
      - PORT=6000 # 你想用的端口
      - AUTH_URL=http://localhost:6000 # 配置 Github 授权回调地址
    # ...
```

**Comment by Y80** [comment]
你访问网站是通过 `http://localhost:6000` 地址吗？

**Comment by qiyue-sanye** [comment]
http://localhost:3090
配置内的端口
访问端口以及github都是这个

**Comment by Y80** [comment]
可以麻烦再完整发下 `docker-compose.yml` 吗

**Comment by zainzl** [comment]
本地账号密码需求+1，目前有纯内网环境部署的需求（不开放互联网访问）

**Comment by Y80** [comment]
> 本地账号密码需求+1，目前有纯内网环境部署的需求（不开放互联网访问）

你的使用场景，是想归纳管理内网的一些网站吗？

**Comment by qiyue-sanye** [comment]
> 可以麻烦再完整发下 吗`docker-compose.yml`

```
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgresql
    environment:
      POSTGRES_DB: bmm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 523f2vmYf4HIwR #自行修改对应DB_DRIVER
    volumes:
      - /vol1/1000/Docker/bmm/postgresql_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bmm"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  bmm:
    image: lcclcc/bmm
    container_name: bmm
    restart: unless-stopped
    environment:
      - DB_DRIVER=postgresql
      - DB_CONNECTION_URL=postgresql://postgres:523f2vmYf4HIwR@postgres:5432/bmm
      - HOST=0.0.0.0
      - PORT=3090  # 修改为3090
      - AUTH_URL=http://localhost:3090 # 配置 Github 授权回调地址
    ports:
      - "3090:3090"  # 修改为3090:3090
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
      echo '等待数据库准备就绪...';
      while ! nc -z postgres 5432; do
        echo '数据库端口尚未开放，等待...';
        sleep 2;
      done;
      echo '数据库端口已开放，启动应用...';
      pnpm start --port 3090  # 确保使用3090端口
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3090/health"]  # 修改为3090
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
```

**Comment by Y80** [comment]
@qiyue-sanye 
你的 AUTH_GITHUB_ID/AUTH_GITHUB_SECRET 用的是项目自带的，还是你自己配置的，如果是你自己的，Authorization callback URL 应该配置为 `http://localhost:3090` 或 `http://localhost`，可以检查下。

**Comment by qiyue-sanye** [comment]
使用docker compose 配置正常运行，正常授权

```
services:
  bmm:
    image: lcclcc/bmm
    container_name: bmm
    restart: unless-stopped
    ports:
      - "3090:3000" #3090为外部访问端口，可选
    environment:
      - DB_DRIVER=sqlite
      - DB_CONNECTION_URL=file:/app/volume/sqlite.db
      - AUTH_URL=填写最后访问的地址需要与oauth中两个地址相同
      - AUTH_GITHUB_ID=填写创建的oauth内的Client ID，必填项
      - AUTH_GITHUB_SECRET=填写创建的oauth内的Client secrets，没有先生成一个，必填项
    volumes:
      - bmm:/app/volume #bmm可改成需要存放的地址，可选

volumes:
  bmm:
```

github授权始终不方便，账号密码登录，如果感觉不安全，可以增加TOTP两部验证的可选项嘛。想用手机操作的时候属实不方便
